name = "wb-tiktok"
main = "src/index.js"
compatibility_date = "2024-02-19"

[observability]
enabled = true

# Konfigurasi tambahan untuk memastikan asset terkirim dengan benar
[site]
bucket = ""
entry-point = "src"